### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by eoinmurray** [rinocloud/rinocloud-matlab#17]
If anything goes wrong at the moment the error output is simply 

```
>>> 'Could not connect to Rinocloud'
>>> 'error;
```

This makes the library impossible to debug. We need to throw detailed errors. 

Maybe just let the program crash, the library should after all not crash if used correctly.

**Comment by jamie47** [comment]
wrt this bug - matlab automatically gives error messages, I've sort of overridden that. 

The idea is that if the internet goes down, the whole script does not crash (imagine how annoying it would be to lose a few days of simulation data due to patchy wifi).

Yes, the library should not crash if used properly, but the internet can still go down and the errors within the functions are mostly for us. I'm minded to to keep the error output as is for the time being. Obviously I'll go through and put detailed error messages in as warnings, but the point is that your simulation or lab control system shouldn't quit due to connectivity problems.

Fixing the JSONLAB one now ...
